version: "3.7"
services:
  neo4j_full:
    image: neo4j:4.4
    container_name: neo4j_full
    ports:
      - "17474:7474"
      - "17687:7687"
    volumes:
    - ${IMDB_DATA}:/var/lib/neo4j/import:ro
    mem_limit: 4g
    user: '1000'
    environment:
      JAVA_OPTS: "-Xms4g -Xms4g"
      NEO4J_AUTH: "none"
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_dbms_memory_heap_maxSize: 3G
      NEO4J_dbms_memory_heap_max__size: 3G
      NEO4J_dbms_memory_heap_initial__size: 1G
