spring:
  application:
    name: 'IMDb Search'

  neo4j:
    uri: 'bolt://localhost:7687'
    authentication:
      username: neo4j

server:
  port: 8769

springdoc:
  swagger-ui:
    path: '/swagger-ui.html'
  api-docs:
    path: '/api-docs'